In [23]:
# Import the packages
import torch
import os
import argparse
import numpy as np
import os.path as osp
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import normalize
from tqdm import tqdm
#from torcheval.metrics import R2Score # To be implemented
import torch.nn as nn
import torch.nn.functional as F
from torch.nn import Linear
from torch.nn import BatchNorm1d
import torch.optim as optim

from aux_func import*
from datset_process import *
from torch.utils.data import DataLoader

# Import the pretrained default model resnet18/resnet50/resnet101
from torchvision.models import resnet50
from MODEL.model import resnet12

In [24]:
# Define arg parser
seed=200
paser = argparse.ArgumentParser()
args = paser.parse_args("")
np.random.seed(200)
torch.manual_seed(seed)
device=input("Enter cuda or cpu for device type")
device = torch.device(device)
#'cuda' if torch.cuda.is_available() else
device

device(type='cpu')

In [25]:
# Take user inputs 
args.dataset='miniimagenet'
args.data_path='datasets/mini-imagenet/'
args.num_classes=64 # By default for miniimagenet
args.image_size=84

# FSL definitions
args.num_ways=5 # Number of classes per batch
args.k_shot=5 # number of Images per class
args.query=15 # Query set of the FSL
args.unlabel=50 # Number of unlabel samples per class 
args.steps=5 # Select how many unlabeled data for each class in one iteration.
args.threshold=0.2  # Since we have 5 classes in each support set. So if all the classes are equally probable then mininmum p=0.2

# set in semi-supervised few-shot learning
num_support = args.k_shot * args.num_ways
num_query = args.query * args.num_ways
num_unlabeled = args.unlabel * args.num_ways

# Training or testing definitions 
args.episodes=600

In [26]:
# Number of sets of unlabeled data
num_select = int(args.unlabel / args.steps)

In [27]:
# Import the resnet model and define the model to be used 
model=resnet50(num_classes=args.num_classes,pretrained=False)
#model=resnet12(args.num_classes)

# define last layer

'''
The input shape of last layer is found from the output shape of the resnet layer defined as 
'''
# in_channels=2048*3*3 out_channels=args.num_ways
last_layer=nn.Linear(2048,args.num_ways,bias=True)
print(model)
model.fc = nn.Flatten()
print(model)

c:\Users\kanad\Desktop\Github repos\ME_793_PROJECT\793_env\lib\site-packages\torchvision\models\_utils.py:208: UserWarning: The parameter 'pretrained' is deprecated since 0.13 and will be removed in 0.15, please use 'weights' instead.
  warnings.warn(
c:\Users\kanad\Desktop\Github repos\ME_793_PROJECT\793_env\lib\site-packages\torchvision\models\_utils.py:223: UserWarning: Arguments other than a weight enum or `None` for 'weights' are deprecated since 0.13 and will be removed in 0.15. The current behavior is equivalent to passing `weights=None`.
  warnings.warn(msg)


ResNet(
  (conv1): Conv2d(3, 64, kernel_size=(7, 7), stride=(2, 2), padding=(3, 3), bias=False)
  (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  (relu): ReLU(inplace=True)
  (maxpool): MaxPool2d(kernel_size=3, stride=2, padding=1, dilation=1, ceil_mode=False)
  (layer1): Sequential(
    (0): Bottleneck(
      (conv1): Conv2d(64, 64, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn1): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv2): Conv2d(64, 64, kernel_size=(3, 3), stride=(1, 1), padding=(1, 1), bias=False)
      (bn2): BatchNorm2d(64, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (conv3): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 1), bias=False)
      (bn3): BatchNorm2d(256, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
      (relu): ReLU(inplace=True)
      (downsample): Sequential(
        (0): Conv2d(64, 256, kernel_size=(1, 1), stride=(1, 

In [28]:
#  Get the features from the resnet model

def get_features(model,input):
    '''
    The function first checks if the input batch size exceeds a desired batch size. If it does, the input batch is split into smaller batches of size 64, and the 
    ResNet model is called on each smaller batch using the model function with the return_feat=True argument to return the output features in addition to the classification results. 
    The output features are then detached from the computation graph, transferred to the CPU, and appended to a list embed. 
    Once all batches have been processed, the list of output features is concatenated using torch.cat to form a single tensor embed.
    If the input batch size is less than or equal to the desired batch size, the ResNet model is called once with the input batch using the model function with the return_feat=True argument to return the output features.
    Finally, the function checks if the shape of the output features embed matches the shape of the input batch, and returns the output features as a NumPy array using the numpy() method.
    '''
    batch_size = 32  # Use the desired batch size
    input = torch.tensor(input)
    
    # Check to prevent the input shape from exceeding the desired batch size
    if input.shape[0] > batch_size:
        embed = []
        i = 0
        while i <= input.shape[0]-1:
            embed.append(model(input[i:i+batch_size])) # Changed. Check
            i += batch_size
        embed = torch.cat(embed)
    else:
        embed = model(input) # Changed. Check. Removed return feat
    assert embed.shape[0] == input.shape[0] # Check if input shape = embed shape  as we will be working on input shape.
    return embed.detach().numpy()

In [29]:
def train_loop(model1, dataset, loss_fn, optimizer, inputs, targets):
    # Define forward function
    def forward_fn(data, label):
        logits = model1(data)
        print(logits)
        loss = loss_fn(logits, label) + entropy_loss(logits) # Combination of two loss functions used here. The entropy_loss act as regularizer
        # loss = loss_fn(logits, label)
        return loss, logits
    
    def train_step(data, label):
        optimizer.zero_grad()
        loss, logits = forward_fn(data, label)
        loss.backward()
        optimizer.step()
        return loss.item(), logits
    
    model.train()
    inputs = torch.tensor(inputs)
    targets = torch.tensor(targets).long() # Changed
    loss, logits = train_step(inputs, targets)
    return loss, logits

In [30]:
def get_preds(out):
    preds = torch.argmin(out, dim=0).item()
    return preds, preds

In [31]:
def get_preds_position_(unlabel_out, position, _postion, thres=0.001):
    length = len(position)
    r = []
    un_idx = []
    for idx in range(length):
        pos = position[idx]
        _pos = _postion[idx]
        _out = unlabel_out[idx][pos]
        out = F.softmax(_out,dim=0)  # Check if dim=0 or 1 # Correct
        #print(out)
        if len(pos)==1:
            un_idx.append(idx)
            continue
        conf =  torch.argmin(out).item()
        conf = out.view(-1)[conf].item()
        #print(conf)
        if conf>thres:
            un_idx.append(idx)
            if len(_pos)==0:
                r.append(torch.argmin(out,dim=1).item().asnumpy())  # check if asnumpy works here or not
            else:
                r.append(_pos[-1])
            continue
        t, _ = get_preds(out)
        a = pos[t]
        _postion[idx].append(a)
        position[idx].remove(a)
        #print(position)
        r.append(a)
    return np.asarray(r), un_idx,_postion,position  # Changed here

In [32]:
# Define the dataset and the respective loaders
args.train_episodes=10
dataset = DataSet( args.image_size, 'train',args.data_path)
sampler = EpisodeSampler(dataset.label, args.train_episodes,args.num_ways, args.k_shot, args.query, args.unlabel)
trainloader = DataLoader(dataset, batch_sampler=sampler,shuffle=False, num_workers=4, pin_memory=True)


In [33]:
# Start the training process 

# in the below code I am not using query set which should be concated with unlabeled data.

for data in tqdm(trainloader):

        # create different sets of data from the train loader
        data = data.cpu()
        targets = torch.arange(args.num_ways).repeat(args.k_shot+args.query+args.unlabel).long()

        #print(data,targets)
    
        support_data = data[:num_support]
        query_data = data[num_support:num_support+num_query]
        unlabel_data = data[num_support+num_query:]

        support_inputs = normalize(get_features(model, support_data))  # get feature embeddings for 
        support_targets = targets[:num_support].cpu().numpy()

        print(support_inputs.shape,support_targets)

        query_inputs = normalize(get_features(model, query_data))
        query_targets = targets[num_support:num_support+num_query].cpu().numpy()

        #print(query_inputs.shape,query_targets.shape)

        unlabel_inputs = normalize(get_features(model, unlabel_data))
        unlabel_targets = targets[num_support+num_query:].cpu().numpy()

        # The classifier has already been decided as linear classifier with a single dense layer and the output dimension=5

        ori_index = [x for x in range(250)]  # Store the index position of 250 images
        _POSITION = [[] for _ in range(250)] # Create a 2D list to store the list of 5 classes in passed along with the image batch.
        POSITION = [[0, 1, 2, 3, 4] for _ in range(250)] # [0,1,2,3,4] was chosen for encoding the 5 classes
        
        # Define the loss criterion and the SGD optimizer used here for initial training of model.
        criterion = nn.CrossEntropyLoss(reduction='mean')
        #print(last_layer.parameters())
        optimizer = torch.optim.SGD(last_layer.parameters(), lr = 1e-3, momentum=0.9, weight_decay=5e-4)  # weight decay is for L2 regularization.

        # Begin initial training

        print('\n********************************************  Initial training the model')
        for epoch in range(100):
              loss,_=train_loop(last_layer, None, criterion, optimizer, support_inputs, support_targets)
              #print(f"Train_Epoch: {epoch}  Train_Loss: {loss}")
        
        # Start of code using complimentary labels
        i=1
        while(True):
            print('\n********************************************  Training with complimentatry labels')
            select_idx=[]
            nl_pred=[]
            unselect_idx=[]
            unlabel_out = last_layer(torch.tensor(unlabel_inputs))
            nl_pred, unselect_idx,_POSITION,POSITION = get_preds_position_(unlabel_out, POSITION, _POSITION, args.threshold)  # Changed
            #print(unselect_idx)
            print(_POSITION)
            select_idx = [x for x in ori_index if x not in unselect_idx]
            _unlabel_embeddings = unlabel_inputs[select_idx]
            #_unlabel_t = unlabel_targets[select_idx]
            nl_pred = nl_pred[select_idx]
            print(nl_pred,i)
            if(len(nl_pred)==0):
                  break
            optimizer_NL = torch.optim.SGD(last_layer.parameters(), lr = 1e-3, momentum=0.9, weight_decay=5e-4)
            for epoch in range(20):
                loss = train_loop(last_layer, None, NL_loss, optimizer_NL, unlabel_inputs, nl_pred)
                #print(f"Epoch: {epoch}  Loss: {loss}")
            
            # Break condition no negative label found below threshold condition
            i=i+1
            
        print(_POSITION) # Printing NULL . Check
        class_num = [0 for _ in range(5)]
        pseudo_label = []
        index_pl = []
        for idx in range(len(POSITION)):
            item = POSITION[idx]
            if len(item) == 1:
                lab = item[0]
                pseudo_label.append(item[-1])
                class_num[lab] += 1
                index_pl.append(idx)
        class_num = [item + 8 for item in class_num]
        max_ = max(class_num) * 1.0
        pseudo_label = np.asarray(pseudo_label)
        t1_ = unlabel_inputs[index_pl]
        t2_ = torch.tensor(pseudo_label, dtype=torch.int64)
        print(t2_)
        for epoch in range(100):
            loss=train_loop(last_layer, None, criterion, optimizer, t1_, t2_)
            print(f"Epoch: {epoch}  Loss: {loss}")   
        



  0%|          | 0/10 [00:00<?, ?it/s]C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)


(25, 2048) [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)
C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)



********************************************  Initial training the model
tensor([[ 0.0286,  0.0014,  0.0188,  0.0103, -0.0089],
        [ 0.0279, -0.0085,  0.0078,  0.0095, -0.0074],
        [ 0.0258, -0.0040,  0.0050,  0.0038, -0.0162],
        [ 0.0170,  0.0002,  0.0078,  0.0039, -0.0125],
        [ 0.0206, -0.0064,  0.0136,  0.0102, -0.0140],
        [ 0.0244, -0.0023,  0.0105,  0.0019, -0.0159],
        [ 0.0197, -0.0039,  0.0088,  0.0007, -0.0137],
        [ 0.0224, -0.0007,  0.0118,  0.0118, -0.0099],
        [ 0.0203, -0.0035,  0.0027,  0.0039, -0.0228],
        [ 0.0187,  0.0017,  0.0112,  0.0068, -0.0177],
        [ 0.0179, -0.0080,  0.0130,  0.0105, -0.0116],
        [ 0.0178, -0.0007,  0.0039,  0.0145, -0.0038],
        [ 0.0199,  0.0011,  0.0069,  0.0128, -0.0145],
        [ 0.0251,  0.0016,  0.0111,  0.0123, -0.0050],
        [ 0.0172,  0.0023,  0.0036,  0.0095, -0.0130],
        [ 0.0196,  0.0054,  0.0134,  0.0111, -0.0100],
        [ 0.0200, -0.0018,  0.0011,  0.0112, -

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\3623213113.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets).long() # Changed
 10%|█         | 1/10 [00:13<02:02, 13.56s/it]C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)


tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 0  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 1  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 2  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 3  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 4  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 5  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 6  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 7  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)
C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)



********************************************  Initial training the model
tensor([[ 8.6178e-03,  1.0178e-02,  2.6819e-02,  2.0345e-02, -3.8194e-02],
        [ 1.0310e-02,  3.9052e-03,  2.6595e-02,  1.7455e-02, -4.5958e-02],
        [ 3.4139e-02,  1.0475e-02,  1.7764e-02,  1.9450e-02, -4.9133e-02],
        [ 4.4925e-03,  1.8947e-02,  1.8143e-02,  2.1310e-02, -3.1975e-02],
        [ 5.5134e-02,  1.0306e-03,  1.5837e-02,  1.2314e-02, -6.2170e-02],
        [ 2.0888e-02,  4.3663e-03,  2.4152e-02,  1.7267e-02, -4.6127e-02],
        [ 9.1727e-03,  7.3547e-03,  2.7472e-02,  2.6019e-02, -3.9600e-02],
        [ 2.9800e-02,  7.1611e-03,  2.0638e-02,  2.2829e-02, -4.3885e-02],
        [ 1.9087e-02,  6.8894e-03,  2.0329e-02,  2.5796e-02, -4.6376e-02],
        [ 1.5482e-02,  1.1022e-02,  2.8855e-02,  2.4598e-02, -4.6992e-02],
        [ 4.6216e-03,  1.3153e-02,  2.5758e-02,  1.9586e-02, -3.6371e-02],
        [ 1.7492e-02,  3.4789e-04,  2.5436e-02,  2.7242e-02, -3.8390e-02],
        [ 2.8955e-02,  3.0

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\3623213113.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets).long() # Changed
 20%|██        | 2/10 [00:21<01:23, 10.39s/it]

tensor([[ 0.0126,  0.0207,  0.0276,  0.0259, -0.0467],
        [ 0.0292,  0.0014,  0.0260,  0.0186, -0.0504],
        [ 0.0196,  0.0152,  0.0273,  0.0223, -0.0487],
        ...,
        [ 0.0087,  0.0205,  0.0164,  0.0195, -0.0497],
        [ 0.0183,  0.0131,  0.0245,  0.0249, -0.0581],
        [ 0.0220,  0.0067,  0.0236,  0.0210, -0.0486]],
       grad_fn=<AddmmBackward0>)
tensor([[ 0.0129,  0.0210,  0.0279,  0.0262, -0.0481],
        [ 0.0295,  0.0018,  0.0263,  0.0189, -0.0517],
        [ 0.0199,  0.0155,  0.0277,  0.0227, -0.0501],
        ...,
        [ 0.0090,  0.0209,  0.0168,  0.0198, -0.0511],
        [ 0.0187,  0.0135,  0.0248,  0.0253, -0.0595],
        [ 0.0224,  0.0071,  0.0240,  0.0213, -0.0500]],
       grad_fn=<AddmmBackward0>)
tensor([[ 0.0133,  0.0214,  0.0283,  0.0267, -0.0497],
        [ 0.0299,  0.0021,  0.0267,  0.0193, -0.0533],
        [ 0.0203,  0.0159,  0.0281,  0.0231, -0.0517],
        ...,
        [ 0.0094,  0.0212,  0.0172,  0.0202, -0.0527],
        [ 0.0

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)


(25, 2048) [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)
C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)



********************************************  Initial training the model
tensor([[ 0.0334,  0.0221,  0.0344,  0.0314, -0.0983],
        [ 0.0533,  0.0078,  0.0397,  0.0404, -0.0847],
        [ 0.0313,  0.0241,  0.0294,  0.0354, -0.0897],
        [ 0.0280,  0.0197,  0.0344,  0.0271, -0.0858],
        [ 0.0242,  0.0329,  0.0293,  0.0367, -0.0871],
        [ 0.0253,  0.0165,  0.0328,  0.0395, -0.0906],
        [ 0.0329,  0.0142,  0.0381,  0.0198, -0.0924],
        [ 0.0221,  0.0342,  0.0315,  0.0416, -0.0913],
        [ 0.0258,  0.0278,  0.0343,  0.0316, -0.0858],
        [ 0.0446,  0.0003,  0.0386,  0.0348, -0.0911],
        [ 0.0268,  0.0306,  0.0218,  0.0386, -0.0868],
        [ 0.0244,  0.0203,  0.0282,  0.0313, -0.0982],
        [ 0.0195,  0.0350,  0.0334,  0.0388, -0.0937],
        [ 0.0203,  0.0229,  0.0316,  0.0384, -0.0911],
        [ 0.0268,  0.0202,  0.0307,  0.0278, -0.0894],
        [ 0.0605, -0.0012,  0.0403,  0.0257, -0.0872],
        [ 0.0308,  0.0145,  0.0356,  0.0306, -

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\3623213113.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets).long() # Changed
 30%|███       | 3/10 [00:29<01:02,  8.98s/it]

tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 97  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 98  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 99  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))


C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)


(25, 2048) [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)
C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)



********************************************  Initial training the model
tensor([[ 0.0604,  0.0144,  0.0348,  0.0391, -0.1205],
        [ 0.0371,  0.0299,  0.0347,  0.0394, -0.1262],
        [ 0.0279,  0.0296,  0.0473,  0.0436, -0.1412],
        [ 0.0382,  0.0289,  0.0450,  0.0417, -0.1283],
        [ 0.0398,  0.0323,  0.0513,  0.0424, -0.1402],
        [ 0.0476,  0.0235,  0.0406,  0.0454, -0.1283],
        [ 0.0547,  0.0276,  0.0399,  0.0456, -0.1356],
        [ 0.0372,  0.0283,  0.0488,  0.0425, -0.1315],
        [ 0.0278,  0.0332,  0.0512,  0.0469, -0.1306],
        [ 0.0562,  0.0193,  0.0437,  0.0467, -0.1295],
        [ 0.0543,  0.0222,  0.0415,  0.0393, -0.1305],
        [ 0.0270,  0.0284,  0.0395,  0.0512, -0.1272],
        [ 0.0344,  0.0262,  0.0488,  0.0440, -0.1294],
        [ 0.0415,  0.0278,  0.0506,  0.0334, -0.1291],
        [ 0.0444,  0.0345,  0.0440,  0.0361, -0.1339],
        [ 0.0366,  0.0363,  0.0452,  0.0353, -0.1327],
        [ 0.0457,  0.0243,  0.0501,  0.0376, -

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\3623213113.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets).long() # Changed
 40%|████      | 4/10 [00:35<00:48,  8.17s/it]C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)


tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 73  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 74  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 75  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 76  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 77  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 78  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 79  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 80  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)
C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)



********************************************  Initial training the model
tensor([[ 0.0550,  0.0327,  0.0491,  0.0435, -0.1628],
        [ 0.0828,  0.0249,  0.0346,  0.0469, -0.1577],
        [ 0.0315,  0.0467,  0.0655,  0.0527, -0.1691],
        [ 0.0378,  0.0444,  0.0642,  0.0536, -0.1777],
        [ 0.0338,  0.0503,  0.0684,  0.0612, -0.1734],
        [ 0.0718,  0.0389,  0.0437,  0.0512, -0.1653],
        [ 0.0882,  0.0347,  0.0239,  0.0467, -0.1524],
        [ 0.0446,  0.0392,  0.0658,  0.0523, -0.1750],
        [ 0.0429,  0.0387,  0.0675,  0.0484, -0.1762],
        [ 0.0483,  0.0381,  0.0550,  0.0520, -0.1736],
        [ 0.0353,  0.0406,  0.0679,  0.0612, -0.1761],
        [ 0.0488,  0.0355,  0.0477,  0.0564, -0.1725],
        [ 0.0258,  0.0434,  0.0660,  0.0546, -0.1763],
        [ 0.0446,  0.0381,  0.0597,  0.0587, -0.1736],
        [ 0.0487,  0.0426,  0.0502,  0.0554, -0.1736],
        [ 0.0486,  0.0399,  0.0606,  0.0518, -0.1738],
        [ 0.0355,  0.0377,  0.0655,  0.0491, -

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\3623213113.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets).long() # Changed
 50%|█████     | 5/10 [00:41<00:36,  7.28s/it]

tensor([], dtype=torch.int64)
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 0  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 1  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 2  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 3  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 4  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 5  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 6  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 7  Loss: (nan, tensor([], size=(0, 5), grad_fn=<Addm

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)


(25, 2048) [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)
C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)



********************************************  Initial training the model
tensor([[ 0.0607,  0.0394,  0.0692,  0.0687, -0.2136],
        [ 0.0764,  0.0401,  0.0508,  0.0667, -0.2151],
        [ 0.0472,  0.0395,  0.0817,  0.0690, -0.2171],
        [ 0.0480,  0.0383,  0.0770,  0.0601, -0.2161],
        [ 0.0459,  0.0430,  0.0725,  0.0689, -0.2077],
        [ 0.0801,  0.0397,  0.0476,  0.0591, -0.2018],
        [ 0.0751,  0.0488,  0.0546,  0.0643, -0.2059],
        [ 0.0390,  0.0383,  0.0814,  0.0645, -0.2092],
        [ 0.0464,  0.0418,  0.0794,  0.0665, -0.2094],
        [ 0.0305,  0.0422,  0.0813,  0.0689, -0.2094],
        [ 0.0564,  0.0451,  0.0748,  0.0632, -0.2117],
        [ 0.0641,  0.0454,  0.0592,  0.0614, -0.2140],
        [ 0.0998,  0.0482,  0.0276,  0.0541, -0.1946],
        [ 0.0458,  0.0369,  0.0732,  0.0715, -0.2024],
        [ 0.0753,  0.0473,  0.0502,  0.0655, -0.2011],
        [ 0.0668,  0.0400,  0.0703,  0.0634, -0.2080],
        [ 0.0884,  0.0409,  0.0465,  0.0550, -

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\3623213113.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets).long() # Changed
 60%|██████    | 6/10 [00:47<00:26,  6.74s/it]C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)


tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 46  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 47  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 48  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 49  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 50  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 51  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 52  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 53  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)
C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)



********************************************  Initial training the model
tensor([[ 0.0524,  0.0405,  0.0855,  0.0839, -0.2435],
        [ 0.0579,  0.0388,  0.0868,  0.0812, -0.2366],
        [ 0.0923,  0.0682,  0.0586,  0.0594, -0.2523],
        [ 0.0918,  0.0584,  0.0591,  0.0633, -0.2392],
        [ 0.0575,  0.0398,  0.0823,  0.0837, -0.2414],
        [ 0.0490,  0.0424,  0.0809,  0.0826, -0.2476],
        [ 0.0749,  0.0569,  0.0736,  0.0767, -0.2422],
        [ 0.0529,  0.0402,  0.0808,  0.0766, -0.2402],
        [ 0.0882,  0.0644,  0.0614,  0.0668, -0.2440],
        [ 0.0584,  0.0415,  0.0788,  0.0802, -0.2356],
        [ 0.0600,  0.0436,  0.0880,  0.0780, -0.2400],
        [ 0.0561,  0.0441,  0.0815,  0.0807, -0.2384],
        [ 0.0624,  0.0350,  0.0771,  0.0722, -0.2480],
        [ 0.0786,  0.0559,  0.0699,  0.0731, -0.2443],
        [ 0.0674,  0.0451,  0.0767,  0.0812, -0.2454],
        [ 0.0592,  0.0373,  0.0873,  0.0816, -0.2420],
        [ 0.0517,  0.0386,  0.0889,  0.0816, -

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\3623213113.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets).long() # Changed
 70%|███████   | 7/10 [00:53<00:19,  6.44s/it]

[[4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4], [4],

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)


(25, 2048) [0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4 0 1 2 3 4]


C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)
C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)



********************************************  Initial training the model
tensor([[ 0.0736,  0.0589,  0.0972,  0.0817, -0.2702],
        [ 0.0904,  0.0564,  0.0707,  0.0891, -0.2750],
        [ 0.0651,  0.0516,  0.1053,  0.0734, -0.2741],
        [ 0.0769,  0.0568,  0.0856,  0.0778, -0.2767],
        [ 0.0683,  0.0528,  0.0948,  0.0749, -0.2674],
        [ 0.0638,  0.0516,  0.1023,  0.0714, -0.2632],
        [ 0.0954,  0.0707,  0.0545,  0.0852, -0.2739],
        [ 0.1016,  0.0735,  0.0625,  0.0896, -0.2801],
        [ 0.0730,  0.0554,  0.0923,  0.0679, -0.2647],
        [ 0.0867,  0.0514,  0.0695,  0.0816, -0.2746],
        [ 0.0943,  0.0644,  0.0688,  0.0848, -0.2795],
        [ 0.0812,  0.0606,  0.0721,  0.0862, -0.2685],
        [ 0.0698,  0.0567,  0.0944,  0.0703, -0.2732],
        [ 0.0866,  0.0573,  0.0724,  0.0869, -0.2846],
        [ 0.0974,  0.0677,  0.0624,  0.0832, -0.2768],
        [ 0.0901,  0.0576,  0.0729,  0.0879, -0.2855],
        [ 0.0749,  0.0597,  0.0899,  0.0776, -

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\3623213113.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets).long() # Changed
 80%|████████  | 8/10 [00:58<00:12,  6.23s/it]C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)


tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 36  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 37  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 38  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 39  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 40  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 41  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 42  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 43  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)
C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)



********************************************  Initial training the model
tensor([[ 0.0801,  0.0505,  0.1045,  0.0836, -0.3037],
        [ 0.0846,  0.0703,  0.0925,  0.0905, -0.3066],
        [ 0.0792,  0.0540,  0.1040,  0.0899, -0.3019],
        [ 0.0957,  0.0620,  0.0772,  0.0901, -0.3089],
        [ 0.0840,  0.0542,  0.1030,  0.0889, -0.3097],
        [ 0.0914,  0.0704,  0.0865,  0.0920, -0.3130],
        [ 0.0801,  0.0545,  0.1091,  0.0889, -0.3024],
        [ 0.0886,  0.0667,  0.0894,  0.0976, -0.3148],
        [ 0.1077,  0.0782,  0.0609,  0.0819, -0.3074],
        [ 0.0831,  0.0515,  0.1008,  0.0890, -0.3044],
        [ 0.0911,  0.0620,  0.0867,  0.0960, -0.3019],
        [ 0.0829,  0.0567,  0.1120,  0.0883, -0.3033],
        [ 0.0985,  0.0782,  0.0800,  0.0893, -0.3044],
        [ 0.0765,  0.0588,  0.1082,  0.0856, -0.3025],
        [ 0.0955,  0.0689,  0.0846,  0.0906, -0.3052],
        [ 0.0925,  0.0651,  0.0958,  0.0875, -0.3074],
        [ 0.0827,  0.0619,  0.1080,  0.0846, -

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\3623213113.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets).long() # Changed
 90%|█████████ | 9/10 [01:04<00:06,  6.07s/it]C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)


tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 0  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 1  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 2  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 3  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 4  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 5  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 6  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 7  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)
C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\2955394716.py:13: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  input = torch.tensor(input)



********************************************  Initial training the model
tensor([[ 0.0855,  0.0653,  0.1119,  0.0896, -0.3417],
        [ 0.1094,  0.0648,  0.0838,  0.0974, -0.3379],
        [ 0.0886,  0.0686,  0.1182,  0.0878, -0.3360],
        [ 0.0825,  0.0589,  0.1154,  0.0859, -0.3353],
        [ 0.1125,  0.0724,  0.0804,  0.1059, -0.3364],
        [ 0.1020,  0.0730,  0.1006,  0.1058, -0.3381],
        [ 0.1009,  0.0595,  0.1017,  0.0991, -0.3431],
        [ 0.0927,  0.0723,  0.1127,  0.0911, -0.3408],
        [ 0.0951,  0.0725,  0.1040,  0.0972, -0.3370],
        [ 0.0917,  0.0691,  0.1072,  0.0912, -0.3384],
        [ 0.0948,  0.0742,  0.0966,  0.0973, -0.3336],
        [ 0.1029,  0.0761,  0.0868,  0.0899, -0.3397],
        [ 0.0864,  0.0642,  0.1172,  0.0934, -0.3298],
        [ 0.0875,  0.0684,  0.1128,  0.0918, -0.3359],
        [ 0.0956,  0.0639,  0.1084,  0.0969, -0.3386],
        [ 0.0876,  0.0731,  0.1064,  0.0930, -0.3359],
        [ 0.1069,  0.0686,  0.0914,  0.0926, -

C:\Users\kanad\AppData\Local\Temp\ipykernel_25876\3623213113.py:19: UserWarning: To copy construct from a tensor, it is recommended to use sourceTensor.clone().detach() or sourceTensor.clone().detach().requires_grad_(True), rather than torch.tensor(sourceTensor).
  targets = torch.tensor(targets).long() # Changed
100%|██████████| 10/10 [01:10<00:00,  5.94s/it]

tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 12  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 13  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 14  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 15  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 16  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 17  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 18  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([], size=(0, 5), grad_fn=<AddmmBackward0>)
Epoch: 19  Loss: (nan, tensor([], size=(0, 5), grad_fn=<AddmmBackward0>))
tensor([

100%|██████████| 10/10 [01:10<00:00,  7.08s/it]
